from pathlib import Path
from database import get_all_incidents


REPORT_DIR = Path("reports/generated")


def safe_text(value) -> str:
    if value is None or value == "":
        return "N/A"
    return str(value)


def line(label: str, value) -> str:
    return f"**{label}:** {safe_text(value)}  "


def generate_incident_report(incident: dict) -> str:
    lines = []

    lines.append(f"# Incident Report: {safe_text(incident.get('incident_id'))}")
    lines.append("")
    lines.append("## 1. Executive Summary")
    lines.append("")
    lines.append(line("Title", incident.get("title")))
    lines.append(line("Severity", incident.get("severity")))
    lines.append(line("Risk Score", incident.get("risk_score")))
    lines.append(line("Status", incident.get("status")))
    lines.append(line("Event Time", incident.get("event_time")))
    lines.append("")
    lines.append("This report documents a cloud security alert generated by the Cloud SOC Triage Engine.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 2. Detection Details")
    lines.append("")
    lines.append(line("Incident ID", incident.get("incident_id")))
    lines.append(line("Rule ID", incident.get("rule_id")))
    lines.append(line("Description", incident.get("description")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 3. Entity Context")
    lines.append("")
    lines.append(line("User", incident.get("user_name")))
    lines.append(line("User Role", incident.get("user_role")))
    lines.append(line("Department", incident.get("department")))
    lines.append(line("User Risk", incident.get("user_risk")))
    lines.append(line("Source IP", incident.get("source_ip")))
    lines.append(line("AWS Region", incident.get("aws_region")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 4. Local Enrichment")
    lines.append("")
    lines.append(line("IP Type", incident.get("ip_type")))
    lines.append(line("IP Label", incident.get("ip_label")))
    lines.append(line("IP Reputation", incident.get("ip_reputation")))
    lines.append(line("Business Hours", incident.get("business_hours")))
    lines.append(line("Normal Region", incident.get("normal_region")))
    lines.append(line("Unusual Region", incident.get("unusual_region")))
    lines.append(line("Local Risk Notes", incident.get("local_risk_notes")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 5. MITRE ATT&CK Mapping")
    lines.append("")
    lines.append(line("Tactic", incident.get("mitre_tactic")))
    lines.append(line("Technique ID", incident.get("mitre_technique_id")))
    lines.append(line("Technique Name", incident.get("mitre_technique_name")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 6. Evidence")
    lines.append("")
    lines.append(safe_text(incident.get("evidence")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 7. Recommended Analyst Action")
    lines.append("")
    lines.append(safe_text(incident.get("recommended_action")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 8. Analyst Notes")
    lines.append("")
    lines.append(safe_text(incident.get("analyst_notes")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 9. Case Timeline")
    lines.append("")
    lines.append(line("Created At", incident.get("created_at")))
    lines.append(line("Updated At", incident.get("updated_at")))
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 10. Closure Guidance")
    lines.append("")
    lines.append("Before closing this case, the analyst should confirm:")
    lines.append("")
    lines.append("- The activity was authorized or contained.")
    lines.append("- Any suspicious access keys were disabled or rotated.")
    lines.append("- IAM permission changes were reviewed.")
    lines.append("- CloudTrail logging is enabled and healthy.")
    lines.append("- User credentials and MFA status were verified.")
    lines.append("- Related alerts or attack-chain activity were reviewed.")
    lines.append("")

    return "\n".join(lines)


def generate_all_reports() -> int:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    incidents = get_all_incidents()

    for incident in incidents:
        incident_id = safe_text(incident.get("incident_id"))
        report_path = REPORT_DIR / f"{incident_id}.md"
        report_path.write_text(generate_incident_report(incident))

    return len(incidents)


if __name__ == "__main__":
    count = generate_all_reports()
    print(f"Generated {count} incident report(s) in reports/generated/")
